// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCHtUoUhYLA2K0sqVw0Dxj6HYTGsKu5u6w",
    authDomain: "econaija-30e99.firebaseapp.com",
    projectId: "econaija-30e99",
    storageBucket: "econaija-30e99.appspot.com",
    messagingSenderId: "96705107543",
    appId: "1:96705107543:web:e787247bfc0174e8b6b512",
    measurementId: "G-FHN7WZN6VQ",
  );

  static const FirebaseOptions android = FirebaseOptions(
   apiKey: "AIzaSyCHtUoUhYLA2K0sqVw0Dxj6HYTGsKu5u6w",
    authDomain: "econaija-30e99.firebaseapp.com",
    projectId: "econaija-30e99",
    storageBucket: "econaija-30e99.appspot.com",
    messagingSenderId: "96705107543",
    appId: "1:96705107543:web:e787247bfc0174e8b6b512",
    measurementId: "G-FHN7WZN6VQ",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyCHtUoUhYLA2K0sqVw0Dxj6HYTGsKu5u6w",
    authDomain: "econaija-30e99.firebaseapp.com",
    projectId: "econaija-30e99",
    storageBucket: "econaija-30e99.appspot.com",
    messagingSenderId: "96705107543",
    appId: "1:96705107543:web:e787247bfc0174e8b6b512",
    measurementId: "G-FHN7WZN6VQ",
  );

  static const FirebaseOptions macos = FirebaseOptions(
   apiKey: "AIzaSyCHtUoUhYLA2K0sqVw0Dxj6HYTGsKu5u6w",
    authDomain: "econaija-30e99.firebaseapp.com",
    projectId: "econaija-30e99",
    storageBucket: "econaija-30e99.appspot.com",
    messagingSenderId: "96705107543",
    appId: "1:96705107543:web:e787247bfc0174e8b6b512",
    measurementId: "G-FHN7WZN6VQ",
  );
}
